### ISSUE TITLE
AWS_DEFAULT_PROFILE vs AWS_PROFILE

### ISSUE THREAD

**Issue by colde** [mgoodness/plugin-asp#3]
It seems that while the environment variable used to be named **AWS_DEFAULT_PROFILE** the documentation now states it's **AWS_PROFILE**.

See https://docs.aws.amazon.com/cli/latest/userguide/cli-environment.html and https://onetechnical.wordpress.com/2016/10/07/the-curious-case-of-aws_default_profile/

So while **AWS_DEFAULT_PROFILE** might also work, it seems better to update it to the current standard.

**Comment by ghost** [comment]
Can't finde any mention of 'AWS_PROFILE' in  https://docs.aws.amazon.com/cli/latest/userguide/cli-environment.html

**Comment by olafur-palsson** [comment]
https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/SharedIniFileCredentials.html

Here's a mention of it

**Comment by m-radzikowski** [comment]
Implemented in #5
