### ISSUE TITLE
Setting just AWS_PROFILE and using ~/.aws/config file

### ISSUE THREAD

**Issue by m-radzikowski** [mgoodness/plugin-asp#4]
This is a very useful plugin, a must-have for AWS developers. But I found using it much more obstructive than it's zsh counterpart: https://github.com/ohmyzsh/ohmyzsh/blob/master/plugins/aws/aws.plugin.zsh

**The problem**

From what I see this plugin reads `~/.aws/configuration` file to extract credentials and performs `sts assume-role` call to set `AWS_ACCESS_KEY_ID`, `AWS_SECRET_ACCESS_KEY` and `AWS_SESSION_TOKEN`. This has a drawback of role-based credentials expiration after an hour, like it's mentioned in the readme.

But more important is that according to AWS docs the proper configuration should look like this (see https://docs.aws.amazon.com/cli/latest/topic/config-vars.html and https://docs.aws.amazon.com/credref/latest/refdocs/setting-global-source_profile.html):

```
# In ~/.aws/credentials:
[development]
aws_access_key_id=foo
aws_secret_access_key=bar

# In ~/.aws/config
[profile crossaccount]
role_arn=arn:aws:iam:...
source_profile=development
```

Right now having this configuration will result in `asp` error `Invalid ... profile in ...`

Probably the same case will be when using SSO in AWS CLI v2 (although I cannot confirm this).

**The proposition**

Simplify the plugin behaviour by just setting `AWS_PROFILE` (and `AWS_DEFAULT_PROFILE` for compatibility). Look for profile names in `~/.aws/config` file. This will make the plugin work more like mentioned before zsh version.

@mgoodness what do you think? If you agree I can create PR with changes. Otherwise, please let me know you do not want such changes here and I probably will release this as a separate plugin.

**Comment by mgoodness** [comment]
@m-radzikowski I don't use Fish any more, so this plugin is not actively maintained. If you'd like to take it over, I'd be happy to transfer the repo to you.

**Comment by m-radzikowski** [comment]
@mgoodness ok, I will gladly take it over and maintain 👍
